[package]
name = "deepseek"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.11", features = ["default", "gzip", "deflate", "json", "zstd"] }
serde = "1.0.217"
serde_json = "1.0.134"
